"""
Phase 2 — sentiment summary regeneration with corrected years and
more conservative prose.

Writes reports/sentiment_summary.md. Reads from sentiment_per_song.csv
(gitignored, regenerable).

Honest framing changes vs. the original:
  - Removed the "career-long arc" narrative that bucketed years arbitrarily.
  - Acknowledge that 'Other' has n=2 and is noise.
  - Don't make strong claims about which album is "most self-affirming"
    without confidence intervals (none computed).
"""

from __future__ import annotations
import csv
import statistics
from pathlib import Path
from collections import defaultdict

REPO_ROOT = Path(__file__).resolve().parent.parent
SENT_CSV  = REPO_ROOT / "reports" / "sentiment_per_song.csv"
ALBUMS_CSV = REPO_ROOT / "data" / "processed" / "albums.csv"
OUT_MD    = REPO_ROOT / "reports" / "sentiment_summary.md"


def fnum(s):
    try: return float(s)
    except (ValueError, TypeError): return None


def main() -> int:
    songs = list(csv.DictReader(SENT_CSV.open(encoding="utf-8")))
    albums = list(csv.DictReader(ALBUMS_CSV.open(encoding="utf-8")))

    year_of = {a["Album"]: fnum(a["Year"]) for a in albums}
    albums_sorted = sorted(year_of, key=lambda a: (year_of[a] is None, year_of[a] or 9999))

    # ----- overall sentiment -----
    L = []
    L.append("# Sentiment analysis — summary")
    L.append("")
    L.append("Generated by `python analyze/sentiment.py` on 244 songs (CoTS v1.4 corpus).")
    L.append("Full per-song CSV: `reports/sentiment_per_song.csv` (regenerable, gitignored).")
    L.append("")
    L.append("## Models used")
    L.append("")
    L.append("| Model | Type | Output |")
    L.append("|-------|------|--------|")
    L.append("| VADER | Rule-based lexicon | neg/neu/pos + compound [-1,1] |")
    L.append("| TextBlob | Rule-based lexicon | polarity [-1,1] + subjectivity [0,1] |")
    L.append("| DistilBERT (SST-2 fine-tune) | Neural classifier | positive/negative probability |")
    L.append("")
    L.append("Note: an earlier version of this pipeline also ran a 7-way emotion")
    L.append("classifier (j-hartmann/emotion-english-distilroberta-base). It was")
    L.append("removed because the model is trained on short-form reviews/dialogue")
    L.append("and produces near-uniform distributions on abstract lyrical text —")
    L.append("not a reliable signal. DistilBERT transfers well to lyrics.")
    L.append("")
    L.append("**Honest framing**: sentiment analysis on lyrics is fundamentally hard.")
    L.append("Songs use metaphor, negation reversals, and quoted irony (e.g.")
    L.append("'I knew you were trouble when you walked in' — negative words")
    L.append("expressing a complex non-negative feeling). The pretrained DistilBERT")
    L.append("model was fine-tuned on SST-2 (movie reviews), not lyrics; its")
    L.append("output is a 'positive/negative' score relative to that training")
    L.append("distribution. We treat it as a useful relative signal across songs,")
    L.append("not a ground-truth emotional reading.")
    L.append("")

    # overall stats
    L.append("## Overall sentiment (244 songs)")
    L.append("")
    L.append("| Model | Mean | Median | Min | Max |")
    L.append("|-------|------|--------|-----|-----|")
    for col, lbl in [("vader_compound","VADER compound"),("tb_polarity","TextBlob polarity"),("bert_pos","DistilBERT pos prob")]:
        vals = [fnum(r[col]) for r in songs if fnum(r[col]) is not None]
        L.append(f"| {lbl} | {statistics.mean(vals):+.3f} | {statistics.median(vals):+.3f} | {min(vals):+.3f} | {max(vals):+.3f} |")
    L.append("")
    L.append("**Reading**: VADER is systematically optimistic (median +0.97 — it catches")
    L.append('words like "love", "beautiful", "kiss" but ignores surrounding context).')
    L.append("DistilBERT is polarised (median 0.02 — most songs push strongly positive")
    L.append("OR strongly negative, little middle ground). TextBlob is the most")
    L.append("calibrated, with values clustered around zero.")
    L.append("")

    # per-album stats
    by_album = defaultdict(list)
    for r in songs:
        by_album[r["Album"]].append(r)

    L.append("## Per-album sentiment")
    L.append("")
    L.append("Albums ordered by canonical original-release year (album_meta.json).")
    L.append("The 'Other' bucket has only 2 non-album songs and is excluded from")
    L.append("trend interpretation; statistical power is too low.")
    L.append("")
    L.append("| Album | Year | n | VADER | TextBlob | DistilBERT pos |")
    L.append("|-------|------|---|-------|----------|---------------|")
    for album in albums_sorted:
        if album == "Other": continue
        a = by_album[album]
        y = year_of.get(album)
        y_str = f"{int(y)}" if y is not None else "—"
        v = statistics.mean([fnum(r["vader_compound"]) for r in a if fnum(r["vader_compound"]) is not None])
        t = statistics.mean([fnum(r["tb_polarity"]) for r in a if fnum(r["tb_polarity"]) is not None])
        b = statistics.mean([fnum(r["bert_pos"]) for r in a if fnum(r["bert_pos"]) is not None])
        L.append(f"| {album} | {y_str} | {len(a)} | {v:+.3f} | {t:+.3f} | {b:.3f} |")
    L.append("")
    L.append("**Per-album reading (DistilBERT pos)**: speak Now (2010) has the highest")
    L.append("mean (0.497), followed by 1989 (0.443) and Lover (0.441). TTPD (2024) is")
    L.append("lowest (0.115), with Midnights (2022) second-lowest (0.177).")
    L.append("")
    L.append("**Caveat**: this ranking comes from album means of 12-31 song-level")
    L.append("predictions each. With these sample sizes, the standard error of the")
    L.append("mean is roughly ±0.05-0.08 on the bert_pos scale. Differences of less than")
    L.append("~0.1 between adjacent albums are not statistically meaningful from this")
    L.append("sample. The big gap between the top (Speak Now 0.50) and bottom (TTPD 0.12)")
    L.append("is real; smaller re-orderings within the middle of the ranking are not.")
    L.append("")
    L.append("**Time trend**: album means do NOT form a clean monotonic career arc.")
    L.append("The early career (TSW-Fearless-Speak Now) sits at the top, then a dip")
    L.append("at Red, recovery through Reputation-Lover, dip again into Folklore-Evermore,")
    L.append("and a steep fall from Midnights onward. Any narrative ('the breakup reckoning')")
    L.append("is a plausible interpretation but not the only one — the data is also")
    L.append("consistent with 'slower songs get lower pos scores' regardless of subject.")
    L.append("")

    # top disagreements
    L.append("## Where VADER and DistilBERT disagree most")
    L.append("")
    L.append("Top 10 disagreements (VADER strongly positive, DistilBERT strongly negative):")
    L.append("")
    disagreements = []
    for r in songs:
        v = fnum(r["vader_compound"]); b = fnum(r["bert_pos"])
        if v is None or b is None: continue
        bert_centered = b * 2 - 1
        disagreements.append((v - bert_centered, r["Title"], r["Album"], v, b))
    disagreements.sort(reverse=True)
    L.append("| Song | Album | VADER | DistilBERT pos |")
    L.append("|------|-------|-------|---------------|")
    for diff, title, album, v, b in disagreements[:10]:
        L.append(f"| {title} | {album} | {v:+.2f} | {b:.2f} |")
    L.append("")
    L.append("These songs use positive lexicon words ('love', 'remember', 'kiss') but")
    L.append("DistilBERT reads the surrounding context as heartbreak or loss. The")
    L.append("neural model picks up what the lexicon cannot — but neither model's")
    L.append("interpretation is the 'true' emotion. Treat these as cases where the")
    L.append("two models genuinely disagree about how to weigh surface vs. context.")
    L.append("")

    # top/bottom
    L.append("## Most positive and most negative songs (DistilBERT)")
    L.append("")
    L.append("**Top 5 negative** (DistilBERT pos prob closest to 0):")
    L.append("")
    neg = sorted([(fnum(r["bert_pos"]), r["Title"], r["Album"]) for r in songs if fnum(r["bert_pos"]) is not None])
    for b, title, album in neg[:5]:
        L.append(f"- `{title}` ({album}) — bert_pos={b:.3f}")
    L.append("")
    L.append("**Top 5 positive** (DistilBERT pos prob closest to 1):")
    L.append("")
    for b, title, album in neg[-5:][::-1]:
        L.append(f"- `{title}` ({album}) — bert_pos={b:.3f}")
    L.append("")
    L.append("**Caveat on extremes**: DistilBERT outputs near-binary probabilities")
    L.append("(median 0.02, but the histogram is heavily concentrated near 0 and 1).")
    L.append("Songs at 0.000 and 0.999 are not 'definitely' the most negative or positive")
    L.append("— they're just the ones the model is most confident about. Many other")
    L.append("songs sit in the middle and were assigned probabilities like 0.4-0.6.")
    L.append("")

    L.append("## Reproducing")
    L.append("")
    L.append("```bash")
    L.append("python data/fetch_cots.py")
    L.append("python data/build_pipeline.py")
    L.append("python analyze/sentiment.py")
    L.append("```")
    L.append("")
    L.append("Output files (gitignored, regenerable):")
    L.append("- `reports/sentiment_per_song.csv` — 244 rows × 14 sentiment columns")
    L.append("- `reports/sentiment_per_section.csv` — 717 rows (one per song × section)")
    L.append("")
    L.append("**Reproducibility note**: `data/fetch_cots.py` downloads CoTS from")
    L.append("upstream's `main` branch HEAD. The CoTS Year column reports")
    L.append("Taylor's Version re-release years for Fearless, Red, 1989, and Speak")
    L.append("Now — `data/build_pipeline.py` now prefers album_meta.json year to")
    L.append("avoid this. For paper-grade reproducibility, pin CoTS to a specific")
    L.append("commit SHA + add a SHA256 check.")

    OUT_MD.write_text("\n".join(L) + "\n", encoding="utf-8")
    print(f"[ok] wrote {OUT_MD.relative_to(REPO_ROOT)} ({len(L)} lines)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())