"""
Phase 3 — section-level sentiment analysis.

Reads the per-section sentiment CSV produced by analyze/sentiment.py
(VADER + TextBlob + DistilBERT scored per section) and writes a human-
readable summary of section-level patterns:

  1. Per-section averages (verse vs chorus vs bridge vs ...) across all
     244 songs.
  2. Per-album section averages — does the chorus-vs-verse gap differ
     across albums?
  3. Verse->chorus sentiment jump — which songs have the largest
     DistilBERT jump from verse to chorus? (Headline finding.)
  4. Bridge sentiment — are bridges darker than verses? (Pop-theory
     claim.)

Inputs:
  - reports/sentiment_per_song.csv     (gitignored)
  - reports/sentiment_per_section.csv  (gitignored)

Outputs:
  - reports/section_summary.md         (committed)

Usage:
  python analyze/section_analysis.py
  python analyze/section_analysis.py --limit 20   # top-20 tables only
"""

from __future__ import annotations
import argparse
import csv
import statistics
from collections import defaultdict
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
SONGS_CSV = REPO_ROOT / "reports" / "sentiment_per_song.csv"
SECTIONS_CSV = REPO_ROOT / "reports" / "sentiment_per_section.csv"
ALBUMS_CSV = REPO_ROOT / "data" / "processed" / "albums.csv"
OUT_MD = REPO_ROOT / "reports" / "section_summary.md"


def fnum(s):
    try: return float(s)
    except (ValueError, TypeError): return None


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--limit", type=int, default=15, help="top-N tables size (default 15)")
    args = p.parse_args()

    songs = list(csv.DictReader(SONGS_CSV.open(encoding="utf-8")))
    sections = list(csv.DictReader(SECTIONS_CSV.open(encoding="utf-8")))
    albums = list(csv.DictReader(ALBUMS_CSV.open(encoding="utf-8")))

    print(f"[info] {len(songs)} songs, {len(sections)} section rows, {len(albums)} albums")

    # year lookup for sorting
    year_of = {a["Album"]: fnum(a["Year"]) for a in albums}
    albums_sorted = sorted(year_of, key=lambda a: (year_of[a] is None, year_of[a] or 9999))

    # ============== 1. PER-SECTION AVERAGES ==============
    by_section = defaultdict(lambda: {"vader": [], "tb": [], "bert": []})
    for r in sections:
        by_section[r["Section"]]["vader"].append(fnum(r["vader_compound"]))
        by_section[r["Section"]]["tb"].append(fnum(r["tb_polarity"]))
        by_section[r["Section"]]["bert"].append(fnum(r["bert_pos"]))

    # ============== 2. PER-ALBUM SECTION GAP (chorus - verse, BERT) ==============
    # group by song
    song_sections = defaultdict(dict)  # key -> {section -> row}
    for r in sections:
        k = f"{r['AlbumCode']}:{r['TrackNumber']}:{r['Title']}"
        song_sections[k]["meta"] = {
            "AlbumCode": r["AlbumCode"], "Album": r["Album"],
            "Title": r["Title"], "TrackNumber": r["TrackNumber"],
        }
        song_sections[k][r["Section"]] = r

    # verse->chorus jumps
    jumps = []  # (jump, title, album, verse_bert, chorus_bert)
    for k, ss in song_sections.items():
        if "verse" in ss and "chorus" in ss:
            v = fnum(ss["verse"].get("bert_pos"))
            c = fnum(ss["chorus"].get("bert_pos"))
            if v is None or c is None: continue
            jumps.append((c - v, ss["meta"]["Title"], ss["meta"]["Album"], v, c))

    # per-album average jump (chorus - verse)
    album_jumps = defaultdict(list)
    for j, title, album, v, c in jumps:
        album_jumps[album].append(j)
    album_jump_avg = {a: statistics.mean(album_jumps[a]) for a in album_jumps}

    # ============== 3. BRIDGE DARKNESS ==============
    # bridge bert_pos vs verse bert_pos — pop theory says bridges are darker
    bridge_deltas = []
    for k, ss in song_sections.items():
        if "bridge" in ss and "verse" in ss:
            br = fnum(ss["bridge"].get("bert_pos"))
            ve = fnum(ss["verse"].get("bert_pos"))
            if br is None or ve is None: continue
            bridge_deltas.append((br - ve, ss["meta"]["Title"], ss["meta"]["Album"], ve, br))
    bridge_deltas.sort()

    # ============== WRITE MARKDOWN ==============
    L = []
    L.append("# Section-level sentiment analysis")
    L.append("")
    L.append(f"Generated by `python analyze/section_analysis.py`. Reads the per-section CSV from `analyze/sentiment.py`.")
    L.append("")
    L.append("**Notation**: `bert_pos` is DistilBERT-SST2 positive probability [0,1].")
    L.append("`vader_compound` and `tb_polarity` are rule-based [-1,1].")
    L.append("")

    # ---- 1. per-section ----
    L.append("## 1. Per-section averages (all 244 songs, DistilBERT + rule-based)")
    L.append("")
    L.append("| Section | n | VADER | TextBlob | DistilBERT pos |")
    L.append("|---------|---|-------|----------|---------------|")
    for section in ["verse", "chorus", "bridge", "refrain", "in_out"]:
        if section not in by_section: continue
        vs = [x for x in by_section[section]["vader"] if x is not None]
        ts = [x for x in by_section[section]["tb"] if x is not None]
        bs = [x for x in by_section[section]["bert"] if x is not None]
        L.append(f"| {section} | {len(vs)} | {statistics.mean(vs):+.3f} | {statistics.mean(ts):+.3f} | {statistics.mean(bs):.3f} |")
    L.append("")
    L.append("**Reading (what the data shows, not a theory)**: across all 244")
    L.append("songs, on DistilBERT pos the section averages rank:")
    # dynamic ranking
    rank_rows = []
    for section in ["verse", "chorus", "bridge", "refrain", "in_out"]:
        if section in by_section:
            vs = [x for x in by_section[section]["vader"] if x is not None]
            ts = [x for x in by_section[section]["tb"] if x is not None]
            bs = [x for x in by_section[section]["bert"] if x is not None]
            if bs:
                rank_rows.append((statistics.mean(bs), section, len(bs)))
    rank_rows.sort(reverse=True)
    rank_strs = [f"{s} {m:.3f} (n={n})" for m, s, n in rank_rows]
    L.append(" > ".join(rank_strs) + ".")
    L.append("")
    # show VADER rank too
    rank_vader = []
    for section in ["verse", "chorus", "bridge", "refrain", "in_out"]:
        if section in by_section:
            vs = [x for x in by_section[section]["vader"] if x is not None]
            if vs:
                rank_vader.append((statistics.mean(vs), section, len(vs)))
    rank_vader.sort(reverse=True)
    L.append("On VADER the rank is:")
    L.append(" > ".join(f"{s} {m:+.3f} (n={n})" for m, s, n in rank_vader) + ".")
    L.append("Choruses tend to win on VADER because the model's lexicon treats")
    L.append("hook words ('love', 'want', 'stay') as positive and those words")
    L.append("cluster in choruses. DistilBERT doesn't see that lexical pattern")
    L.append("as strongly — on DistilBERT, choruses often drop below verses.")
    L.append("")
    L.append("The in_out section's higher DistilBERT pos likely reflects its")
    L.append("narrow content: intros often set a positive scene, outros often")
    L.append("resolve. Both are short and simple compared to verse/chorus/bridge")
    L.append("which carry the song's emotional weight. So 'in_out is most")
    L.append("positive' is partially a measurement artifact: less text = simpler")
    L.append("context = the model returns confident mid-positive scores.")
    L.append("")
    L.append("**Caveat**: this is a single-corpus finding (Taylor Swift,")
    L.append("DistilBERT-SST2 fine-tuned on movie reviews). Calling it a")
    L.append("'pop-theory refutation' would overreach — the pattern could be")
    L.append("specific to her writing. We have no comparison corpus of other")
    L.append("songwriters to know.")
    L.append("")

    # ---- 2. per-album chorus-vs-verse gap ----
    L.append("## 2. Per-album verse->chorus jump (DistilBERT pos, chorus minus verse)")
    L.append("")
    L.append("A positive jump means the chorus is more positive than the verse")
    L.append("(common in verse-chorus form, where the chorus carries the")
    L.append("song's main hook). A negative jump means the chorus is darker")
    L.append("than the verse — rarer but not unusual (some songs use a")
    L.append("confessional chorus).")
    L.append("")
    L.append("| Album | n songs | mean jump |")
    L.append("|-------|---------|-----------|")
    for album in albums_sorted:
        if album not in album_jump_avg: continue
        n = len(album_jumps[album])
        j = album_jump_avg[album]
        L.append(f"| {album} | {n} | {j:+.3f} |")
    L.append("")
    # exclude 'Other' (n=2 noise bucket) from headline min/max
    j_for_headline = {a: v for a, v in album_jump_avg.items() if a != "Other"}
    if j_for_headline:
        max_album = max(j_for_headline, key=j_for_headline.get)
        min_album = min(j_for_headline, key=j_for_headline.get)
        L.append(f"**Largest mean jump**: {max_album} (+{j_for_headline[max_album]:.3f}).")
        L.append(f"**Smallest mean jump**: {min_album} ({j_for_headline[min_album]:+.3f}).")
        L.append(f"  (Excluding 'Other' bucket — n=2 non-album songs, -0.466).")
        L.append("")

    # ---- 3. top/bottom verse->chorus jumps (headline) ----
    L.append(f"## 3. Top {args.limit} songs by verse->chorus jump (DistilBERT)")
    L.append("")
    L.append("Songs where the chorus is *much more positive* than the verse.")
    L.append("")
    jumps_pos = sorted([j for j in jumps if j[0] > 0], reverse=True)
    L.append("| Song | Album | verse pos | chorus pos | jump |")
    L.append("|------|-------|-----------|------------|------|")
    for j, title, album, v, c in jumps_pos[:args.limit]:
        L.append(f"| {title} | {album} | {v:.2f} | {c:.2f} | {j:+.3f} |")
    L.append("")
    L.append(f"## 4. Top {args.limit} songs where the chorus is *darker* than the verse")
    L.append("")
    L.append("Songs that invert the standard pop pattern: chorus is more negative than verse.")
    L.append("")
    jumps_neg = sorted([j for j in jumps if j[0] < 0])
    L.append("| Song | Album | verse pos | chorus pos | jump |")
    L.append("|------|-------|-----------|------------|------|")
    for j, title, album, v, c in jumps_neg[:args.limit]:
        L.append(f"| {title} | {album} | {v:.2f} | {c:.2f} | {j:+.3f} |")
    L.append("")

    # ---- 5. bridge darkness ----
    L.append("## 5. Bridge sentiment")
    L.append("")
    n_with_bridge = sum(1 for k, ss in song_sections.items() if "bridge" in ss)
    L.append(f"{n_with_bridge}/{len(song_sections)} songs have a tagged bridge section.")
    L.append("")
    if bridge_deltas:
        darker = sum(1 for d, *_ in bridge_deltas if d < 0)
        pct = 100*darker/len(bridge_deltas)
        # 46% darker / 54% brighter — close to coin flip. Don't claim a 'theory'.
        L.append(f"Of those, **{darker}/{len(bridge_deltas)}** ({pct:.0f}%) have a bridge that's")
        L.append("darker (lower DistilBERT pos) than their verse. Conversely,")
        L.append(f"{len(bridge_deltas)-darker} ({100-pct:.0f}%) have a bridge brighter")
        L.append("than their verse. The split is close to a coin flip on this")
        L.append("corpus — neither the 'bridge-darker' nor the 'bridge-brighter'")
        L.append("claim dominates.")
        L.append("")
        L.append("Note: there is no single 'pop theory' that bridges are")
        L.append("necessarily darker. Different songwriting traditions treat")
        L.append("bridges differently (verse-chorus form often uses them as")
        L.append("tension-builders; some ballads use them as emotional release).")
        L.append("This dataset alone can't adjudicate which tradition Swift")
        L.append("follows most often — only that the average bridge sits higher")
        L.append("than the average verse on this particular sentiment signal.")
        L.append("")
        L.append(f"### Top {min(args.limit, len(bridge_deltas))} songs with the darkest bridges (vs verse)")
        L.append("")
        L.append("| Song | Album | verse pos | bridge pos | delta |")
        L.append("|------|-------|-----------|------------|-------|")
        for d, title, album, ve, br in bridge_deltas[:args.limit]:
            L.append(f"| {title} | {album} | {ve:.2f} | {br:.2f} | {d:+.3f} |")
        L.append("")

    L.append("## Reproducing")
    L.append("")
    L.append("```bash")
    L.append("python analyze/sentiment.py        # produces sentiment_per_section.csv")
    L.append("python analyze/section_analysis.py # this file")
    L.append("```")
    L.append("")
    L.append("Note: this analyzer depends on DistilBERT being scored per-section,")
    L.append("which requires `analyze/sentiment.py` to be at the version that")
    L.append("extends phase B over each section (not just per-song).")

    OUT_MD.parent.mkdir(parents=True, exist_ok=True)
    OUT_MD.write_text("\n".join(L) + "\n", encoding="utf-8")
    print(f"[ok] wrote {OUT_MD.relative_to(REPO_ROOT)} ({len(L)} lines)")

    # also print headline numbers
    print(f"\n=== headline ===")
    if jumps:
        biggest = max(jumps, key=lambda x: x[0])
        smallest = min(jumps, key=lambda x: x[0])
        print(f"biggest verse->chorus jump (more positive in chorus): {biggest[1]} ({biggest[2]})  jump={biggest[0]:+.3f}")
        print(f"biggest verse->chorus drop  (more negative in chorus): {smallest[1]} ({smallest[2]})  jump={smallest[0]:+.3f}")
    if bridge_deltas:
        darkest_bridge = bridge_deltas[0]
        print(f"darkest bridge vs verse: {darkest_bridge[1]} ({darkest_bridge[2]})  delta={darkest_bridge[0]:+.3f}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())